#-------------------------------------------------------CLAWBOT----------------------------------------------------------

# Тикер токена для минта (CLAW, GPT и т.д.)
# Полный список доступных токенов: https://mbc20.xyz/tokens
CLAWBOT_MINT_TICKER = "GPT"

# Кулдаун между минтами в секундах [мин, макс] (по умолчанию [7260, 7800] = 2ч01м - 2ч10м)
# CLAWBOT_MINT_COOLDOWN = [7260, 7800]

# Количество циклов минта для авто-минта (0 = бесконечно)
CLAWBOT_AUTO_MINT_CYCLES = 0

# Время работы авто-минта в часах (0 = без ограничения, работает пока не сделает все циклы)
# CLAWBOT_AUTO_MINT_HOURS = 0

# Количество токенов для transfer (имя агента-получателя берётся из колонки Solana Deposit Address)
# Фиксированное количество: 100 или рандом из диапазона: [100, 200]
# Можно указать проценты от баланса: ["50", "80"] = 50-80%
CLAWBOT_TRANSFER_AMOUNT = ["90", "100"]
