#-------------------------------------------------------CLAWBOT----------------------------------------------------------

# Тикер токена для минта (CLAW, GPT и т.д.)
# Полный список доступных токенов: https://mbc20.xyz/tokens
CLAWBOT_MINT_TICKER = "GPT"

# Кулдаун между минтами в секундах (по умолчанию 7260 = 2ч + 1мин буфер)
# CLAWBOT_MINT_COOLDOWN = 7260
