#---------------------------------------------------METAMASK CONTROL----------------------------------------------------

# Использовать рефкоды для активации аккаунта? (без рефкода 250 поинтов, с ним 500)
METAMASK_USE_REFERRAL_CODE = true

# Диапазон процентов для последующих свапов в цикле (smart swaps).
# Указывается в процентах, чтобы можно было обменивать не 100% токена.
# Для меньшей сибильности можно обменивать не весь объём — так процесс выглядит естественнее.
METAMASK_SWAP_AMOUNT = ["100", "100"]

# Сколько ETH нужно оставить на обратный свап
METAMASK_SWAP_FEE_SUPPORT = [0.0003, 0.0004]

# Доступные для свапов токены к ETH внутри MetaMask
# Чем можно дополнить список: "mUSD", "USDC", "USDT", "LINEA"
METAMASK_AVAILABLE_TOKENS = ["mUSD"]

# Максимальное проскальзывание в процентах для свапов (в %)
METAMASK_SLIPPAGE = 0.5

#--------------------------------------------------------BRIDGE---------------------------------------------------------

# Диапазон сумм USDC для бриджа через Relay
METAMASK_BRIDGE_USDC_AMOUNT = ["100", "100"]

# Диапазон сумм ETH для бриджа через Relay
METAMASK_BRIDGE_ETH_AMOUNT = ["100", "100"]

# Сколько оставить токена на кошельке при бридже из Linea обратно в L2 сети
METAMASK_BRIDGE_OUT_LIMITTER = [0.0, 0.0]

#---------------------------------------------------------CEX-----------------------------------------------------------

# Диапазон сумм USDC для вывода с CEX
METAMASK_CEX_WITHDRAW_USDC_AMOUNT = [200, 300]

# Диапазон сумм ETH для вывода с CEX
METAMASK_CEX_WITHDRAW_ETH_AMOUNT = [0.052, 0.054]

# Диапазон сумм USDC для депозита на CEX
METAMASK_CEX_DEPOSIT_USDC_AMOUNT = ["100", "100"]

# Диапазон сумм ETH для депозита на CEX
METAMASK_CEX_DEPOSIT_ETH_AMOUNT = ["100", "100"]

# Сколько оставить на балансе в сети при депозите USDC на CEX
METAMASK_CEX_DEPOSIT_USDC_LIMITER = [0.0, 0.0]

# Сколько оставить на балансе в сети при депозите ETH на CEX
METAMASK_CEX_DEPOSIT_ETH_LIMITER = [0.0, 0.0]
