#----------------------------------------------------OPINION ORDERS-----------------------------------------------------

# Кол-во циклов покупки продажи через лимитные ордера по одной из ставок ref. OPINION_ORDERS_URL
OPINION_CIRCLE_COUNT = [150, 200]

# Интервал проверки состояния открытого ордера (актуальная цена в стакане/заполнение)
OPINION_MONITOR_SLEEP = 60

# Надбавка к цене продажи. Пример: Покупка по цене 80$, при OPINION_MIN_MARGIN_PRICE = 0.1, продажа по 80.1$
OPINION_MIN_MARGIN_PRICE = 0.1

# Ссылка, исход и название ставки на событие. Если исход один, название можно указать - ""
OPINION_ORDERS_URL = [
#    ["https://app.opinion.trade/detail?topicId=71&type=multi", "YES", "November 30"],
    ["https://app.opinion.trade/detail?topicId=1463", "NO", ""]
]

# Флаг для выбора стратегии продажи
# True - продавать по минимальной цене (цена покупки + 0.1)
# False - продавать по рыночной цене
OPINION_USE_LOWEST_SELL_PRICE = false

# Стоп-лосс в пунктах (центах)
# Например, 0.5 означает, что если цена упадет на 0.5¢, позиция будет закрыта по маркету
# 0 - стоп-лосс отключен
OPINION_PRICE_STOP_LOSS = 0

# Таймаут в секундах для перехода на маркет ордер
# Если ордер на продажу не исполнится за это время, будет выполнен маркет ордер
# 0 - таймаут отключен
OPINION_MARKET_ORDER_TIMEOUT = 0

# Максимальный допустимый убыток в процентах от цены покупки
# Если текущая рыночная цена ниже этого порога, ордер НЕ будет выставлен (ожидание экспирации)
# Например: купили по 90¢, при MAX_LOSS_PERCENT = 5 минимальная допустимая цена продажи = 85.5¢
# Если рыночная цена ниже 85.5¢, скрипт не будет выставлять ордер и будет ждать экспирации
# 0 - проверка отключена (всегда выставлять ордер)
OPINION_MAX_LOSS_PERCENT = 0

# Минимальный процент от ожидаемых SHARES для считывания ордера частично выполненным
# Например, 50 означает что при получении 50% от ожидаемых SHARES ордер считается выполненным
# 100 - требуется получить все ожидаемые SHARES
OPINION_BUY_ORDER_FILL_PERCENTAGE = 50

# Время сна в секундах между покупкой и продажей позиции для модуля opinion_process_market_position
OPINION_MARKET_WAIT_TIME = 60

#---------------------------------------------------OPINION DEPOSIT-----------------------------------------------------

# Минимальный баланс для запуска депозита, если будет больше - софт пропустит депозит
OPINION_MIN_BALANCE = 100

# Диапозон сумм для депозита на Opinion с основного кошелька
OPINION_USDT_DEPOSIT_AMOUNT = ["100", "100"]

# Диапозон сумм для размещений ордеров
OPINION_ORDER_AMOUNT = ["100", "100"]

#---------------------------------------------------------CEX-----------------------------------------------------------

# Диапазон сумм USDT для вывода с CEX
OPINION_CEX_WITHDRAW_USDT_AMOUNT = [150, 180]

# Диапазон сумм BNB для вывода с CEX
OPINION_CEX_WITHDRAW_BNB_AMOUNT = [0.011, 0.013]

# Диапазон сумм USDT для депозита на CEX
OPINION_CEX_DEPOSIT_BNB_AMOUNT = ["100", "100"]

# Диапазон сумм BNB для депозита на CEX
METAMASK_CEX_DEPOSIT_ETH_AMOUNT = ["100", "100"]

# Сколько оставить на балансе в сети при депозите USDT на CEX
OPINION_CEX_DEPOSIT_USDT_LIMITER = [0.0, 0.0]

# Сколько оставить на балансе в сети при депозите BNB на CEX
OPINION_CEX_DEPOSIT_BNB_LIMITER = [0.0, 0.0]
