CLASSIC_ROUTES_BLOCKS_COUNT = [3, 3]

CLASSIC_ROUTES_MODULES_USING = [
    ['cex_withdraw'],
    ['ethereum_bridge_relay_into'],
    ['ethereum_transfer_eth_to_myself', 'ethereum_transfer_eth_to_random'],
    [
        ["ethereum_wrap_eth"],
        ["ethereum_unwrap_eth"],
    ],
    [
        ['ethereum_random_approve']
    ],
    [
        ['ethereum_bridge_relay_dust']
    ],
    ['ethereum_transfer_eth_to_deposit']
]
