CLASSIC_ROUTES_BLOCKS_COUNT = [2, 2]


CLASSIC_ROUTES_MODULES_USING = [
    ["abstract_smart_bridge_eth_relay_in", "abstract_smart_bridge_eth_jumper_in"],
    ["abstract_link_social"],
    [
        ["abstract_vote_random_app"],
    ],
    [
        ["abstract_smart_swaps"],
    ],
    ["abstract_claim_badges"],
    ['abstract_bridge_eth_jumper_out'],
    ['cex_deposit']
]